version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce_admin_sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuperSecureAdminPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
